In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
arr1 = np.array([1, 2, 3, 4])

In [4]:
print(arr1)

[1 2 3 4]


In [6]:
reshaped = np.arange(1, 10).reshape((3, 3))

In [7]:
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
x = np.array([1, 2, 3])


In [9]:
print(x)


[1 2 3]


In [14]:
x_rv= x.reshape(1, 3)

In [15]:
print(x_rv)

[[1 2 3]]


In [16]:
x_cv = x.reshape((3, 1))


In [17]:
print(x_cv)

[[1]
 [2]
 [3]]


In [1]:
np.lins

NameError: name 'np' is not defined

In [2]:
import pandas as pd