In [1]:
import numpy as np

arr = np.arange(0,10,1)
print("The Array")
print(arr)

new_arr1 = arr[1:7] # This command selects a range of elements from the array
print("\nThe new sliced array")
print(new_arr1)

new_arr2 = arr[:] # This command selects all elements in the array
print("\nThe new sliced array with all elements")
print(new_arr2)

The Array
[0 1 2 3 4 5 6 7 8 9]

The new sliced array
[1 2 3 4 5 6]

The new sliced array with all elements
[0 1 2 3 4 5 6 7 8 9]


In [3]:
new_arr3 = arr[3:] # This command selects a range of elements from the array
print("\nThe new sliced array")
print(new_arr3)


The new sliced array
[3 4 5 6 7 8 9]


In [6]:
import numpy as np
# Declare a 2-D array
arr2d = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print("The Array")
print(arr2d)

print("\nElement at row 0 and column 1")
print(arr2d[0][1])

print("\nElements in a range of last two rows & columns")
print(arr2d[1:3, 0:2])

arr2d[1:3, 1:3] = 20
print("\nNew 2D array after changing last two rows & columns values")
print(arr2d)

The Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 0 and column 1
2

Elements in a range of last two rows & columns
[[4 5]
 [7 8]]

New 2D array after changing last two rows & columns values
[[ 1  2  3]
 [ 4 20 20]
 [ 7 20 20]]


In [8]:
import numpy as np

arr = np.arange(0,10,1)
print("The Array")
print(arr)

new_arr = arr[1:7]
print("\nThe new sliced array")
print(new_arr)

new_arr[:] = 20
print("\nThe Original array")
print(arr)

The Array
[0 1 2 3 4 5 6 7 8 9]

The new sliced array
[1 2 3 4 5 6]

The Original array
[ 0 20 20 20 20 20 20  7  8  9]


In [14]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

# shape of a
print(a.shape)

# dimensions of a
print(a.ndim)

# data type of a
print(a.dtype.name)

# item size of a
print(a.itemsize)

# size of a
print(a.size)

# type of a
print(type(a))

b = np.array([6, 7, 8])

print(b)

# type of b
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [15]:
import numpy as np

arr = np.arange(0,10,1) # Generate array with numbers from 0 to 9
print(arr)

print(arr[5]) # Fetch element at index 5

print(arr[0:6]) # Fetch elements in a range

arr[0:6] = 20 # Assign a value to a range of elements
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[0 1 2 3 4 5]
[20 20 20 20 20 20  6  7  8  9]


In [16]:
import numpy as np
# Declare a 2-D array
arr2d = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print("The Array")
print(arr2d)

print("\nElement at row 0 and column 1")
print(arr2d[0][1])

print("\nElements in a range of last two rows & columns")
print(arr2d[1:3, 1:3])

arr2d[1:3, 1:3] = 20
print("\nNew 2D array after changing last two rows & columns values")
print(arr2d)

The Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 0 and column 1
2

Elements in a range of last two rows & columns
[[5 6]
 [8 9]]

New 2D array after changing last two rows & columns values
[[ 1  2  3]
 [ 4 20 20]
 [ 7 20 20]]


In [17]:
import numpy as np

arr = np.arange(0,10,1)
print(arr)

new_arr = arr[1:7].copy()
print(new_arr)

new_arr[:] = 20
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
# Creating 2-D array
arr = np.arange(0,50,1).reshape(10,5) # Declare a 2-D array

print(arr)

print(arr.transpose()) # Print the transposed array
#print(arr.T) # This can also be used and same result will be produced

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]


In [22]:
import numpy as np
# Declare 2 arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([500, 600, 700, 800])

cond = np.array([False, True, False, False]) # Create an array with bool operators

res = np.where(cond, arr1, arr2) # apply the where condition
print(res)

[500  20 700 800]


In [23]:
import numpy as np

arr1 = np.random.randn(7)

print("The original array:")
print(arr1)

np.save('saved_arr',arr1) # save the array 

arr2 = np.load('saved_arr.npy') # load the saved array from file

print("\nThe array loaded from file:")
print(arr2)

The original array:
[-0.42660496 -1.80750271 -1.14001914  0.20099781  0.24634262 -0.07960799
  0.37277748]

The array loaded from file:
[-0.42660496 -1.80750271 -1.14001914  0.20099781  0.24634262 -0.07960799
  0.37277748]


In [24]:
import numpy as np

arr1 = np.random.randn(7)

print("The original array:")
print(arr1)

np.save('saved_arr',arr1) # save the array 

arr2 = np.load('saved_arr.npy') # load the saved array from file

print("\nThe array loaded from file:")
print(arr2)

The original array:
[ 0.2468156  -0.91085559 -1.49965914 -0.14782175 -0.77209722 -0.04307992
 -1.49262856]

The array loaded from file:
[ 0.2468156  -0.91085559 -1.49965914 -0.14782175 -0.77209722 -0.04307992
 -1.49262856]


In [25]:
multi_1 = np.arange(12).reshape(3, 4)
print(multi_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
def getMinMax(arr):
  
  res = []
  
  for i in range(arr.shape[0]): # Traverse over each row
    
    res.append(arr[i].min()) # Store minimum element in list
    
    res.append(arr[i].max()) # Store maximum element in list
    
  return res

# Test Code
arr = np.random.randint(1,100, size=(5,5))

print("The Original Array:")
print(arr)

res_arr = getMinMax(arr)

print("\nThe Resultnt list with min & max values:")
print(res_arr)

The Original Array:
[[25 67 71 45 61]
 [56 16 53 36 47]
 [64 10 85 27 74]
 [42  6 16 41 21]
 [44 60 54 39 87]]

The Resultnt list with min & max values:
[25, 71, 16, 56, 10, 85, 6, 42, 39, 87]
